### ISSUE TITLE
Week 5 Exercise

### ISSUE THREAD

**Issue by ajklinker** [okichris90/christianokitondo-MADA-portfolio#3]
Hey Chris! Your plots were super cool and I thought the topic/visualizations were really insightful. I love that you were able to move the legend around the graph - that's something I'll keep in mind for my future plots. My comments here are only about how to get the graph "exact" to what they published online, but nothing super serious. 

First, your plot arranged the most common method (gunfire) on top, while the published one has it on bottom. This can be adjusted by using `+ guides(fill = guide_legend(reverse=TRUE))` or `geom_area(aes(), data, position = position_fill(reverse = TRUE))`.

Next, some of your colors blended together which can make it hard to distinguish between the types. This is super common and an easy fix. You can add a `+geom_line (aes())` call to create an outline and/or ggplot has a ton of cool built-in pallettes that make it easy to use pretty colors with the `scale_fill_brewer()` from the `RColorBrewer` package. A gallery of all the options can be found [here](https://www.datanovia.com/en/blog/the-a-z-of-rcolorbrewer-palette/) or [here](https://r-graph-gallery.com/38-rcolorbrewers-palettes.html). 

Hope this helps!

**Comment by okichris90** [comment]
Thank you for your feedback Abbie.
